### ISSUE TITLE
Inform about IP Range

### ISSUE THREAD

**Issue by philippkreis-cobra** [ionos-deploy-now/documentation#53]
Which IP Ranges are used by the deployed sites / apps? 
Used for security/firewall rule definition.

**Comment by ionos-deploy-now-support** [comment]
The list of IP addresses used by Deploy Now projects for outbound connections is as follows:
82.165.80.0/24
82.165.81.0/24
82.165.82.0/24
82.165.83.0/24
82.165.84.0/24
82.165.85.0/24
82.165.86.0/24
82.165.87.0/24
82.165.88.0/24
82.165.89.0/24

You can also find these details and more information about Deploy Now here:
https://docs.ionos.space/docs/faq/#which-ips-or-ip-range-is-used-by-deployed-website-and-apps-for-outbound-connections
