### ISSUE TITLE
Add Quarto as a framework sample

### ISSUE THREAD

**Issue by de-barros** [ionos-deploy-now/documentation#72]
[Quarto](https://quarto.org/) has become the go-to framework for creating static sites in R. Could you add Quarto as one of your [framework samples](https://docs.ionos.space/docs/framework-samples/#html-sample)? [Here](https://github.com/quarto-dev/quarto-actions) is a repo to related GitHub actions.

Adding @agaengel @Robert95Sch

**Comment by de-barros** [comment]
Mart at customer support told me: 

`Upon further checking, there is no option to manually set up the new project for Quarto Framework. However, you may try contacting our dedicated Deploy now team via email at deploynow-support@ionos.com
`

I'll send an email. This seems strange, though---see [here](https://quarto.org/docs/publishing/) for major platforms supporting Quarto (such as Netlify). 

It would be great if you could add the framework sample! Thanks for your help

**Comment by ionos-deploy-now-support** [comment]
Hey @de-barros,
thank you for your feedback. We packed adding Quarto to our supported framework in our backlog. 
Unfortunately, I cannot guarantee implementation at the moment.

Best
Chris
