### ISSUE TITLE
Describe how to configure a staging environment

### ISSUE THREAD

**Issue by manuelsucco** [ionos-deploy-now/documentation#75]
Trying to set up a staging environment from a successfully deployed `main` branch fails with the following error:

> **This branch currently does not contain workflow configuration files.**
> You will have to rebase or merge the configuration manually from another branch.

I have no idea, though, which configuration to rebase or merge. The files are - so far - exactly the same in the `stagingOne` branch.

<img width="586" alt="Bildschirmfoto 2023-12-03 um 16 43 17" src="https://github.com/ionos-deploy-now/documentation/assets/53469373/5b168e77-3cb6-4dff-bd4b-77b8ea24cd87">

**Comment by windsaenger** [comment]
Hey @manuelsucco,
we will look at your project and come back to you. 
Best 
Chris

**Comment by manuelsucco** [comment]
Hey Chris,

thanks for the quick reply but have you found anything out by now?

Or do you need more information?

Cheers and happy new year!

**Comment by ionos-deploy-now-support** [comment]
After reviewing some details, it seems you were able to resolve the issue and deploy your projects successfully. If you need any further assistance, please don't hesitate to reach out via email at deploynow-support@ionos.com
