### ISSUE TITLE
Error with config files in setup: DB_xxx could not be found 

### ISSUE THREAD

**Issue by michaelyahoo** [ionos-deploy-now/documentation#77]
I can see the following when I try to setup a new project with Deploy Now:
![image](https://github.com/ionos-deploy-now/documentation/assets/166611837/3323cbc6-e48f-413d-a4bc-a85ab0b91d77)

Then at step "Deploy to IONOS" I can see the following error message:
![image](https://github.com/ionos-deploy-now/documentation/assets/166611837/cbdebcf0-1f50-41f9-a6af-cfab72094081)

What am I doing wrong?

**Comment by ionos-deploy-now-support** [comment]
After reviewing the details, it seems you were able to resolve the issue and deploy your projects successfully. If you need any further assistance, please don't hesitate to reach out to us again
