### ISSUE TITLE
Correct link to support 

### ISSUE THREAD

**Issue by k2lh** [ionos-deploy-now/documentation#79]
At the bottom of https://docs.ionos.space/docs/deployment-configuration/#need-help, the text says

Feel free to reach out to us via [deploynow-support@ionos.com](mailto:someone@yoursite.com).

...and as you can see, the mailto goes to a dummy address. It needs to go to the actual address in the text, thanks.

**Comment by Ap3rtur3** [comment]
Thank you for catching this issue, it is fixed now 👍 

Best regards,
Marcel
